- name: install and run mongodb
  hosts: web
  become: yes #it will get root access
  tasks:
  - name: install mongodb package
    ansible.builtin.package:
      name: mongodb
      state: present
  - name: run mongodb
    ansible.builtin.service:
      name: mongodb
      state: started