- name: install and run nginx
  hosts: web
  become: yes #it will get root access
  tasks:
  - name: install nginx package
    ansible.builtin.package:
      name: mongodb
      state: present
  - name: run nginx
    ansible.builtin.service:
      name: mongodb
      state: started