- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: install or unintall packages
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'git', state: 'present'} # to install git
    - {name: 'mysql', state: 'absent'} # to unistal mysql
    - {name: 'postfix', state: 'absent'} # to uninstall postfix
    - {name: 'nginx', state: 'present'} # to install nginx